import { m } from 'framer-motion';
import { useState, useEffect, useRef } from 'react';
import MainLayout from '../layout/MainLayout';
import CTASection from '../sections/CTASection';
import { Seo } from '../../seo';

const GREEN = "#4aab6d";
const DARK = "#111827";

const sections = [
  {
    id: "objective",
    title: "Objective & Scope",
    content: `100xprompt is committed to protecting Users' privacy and appropriately and responsibly using collected data. By way of this Privacy Policy, we aim to provide you a summary of our privacy practices regarding personal data that we collect and process of/about the User through various sources.

The primary focus of this Privacy Policy is on the personal data collected and processed. Depending on the purposes of processing and your relationship with us as a data subject, we may provide additional customized privacy policies.

This Privacy Policy covers the categories of personal data collected, how we use or process such data, who are the recipients of such data, and your associated rights under applicable laws.`
  },
  {
    id: "data-collected",
    title: "Data Collected",
    content: `We collect personal data of the User, as detailed further in this clause, and as expressly set forth in this Privacy Policy. While some User data has to be mandatorily provided for your use of the Offerings, others are optional and certain portions of the data will remain private; 100xprompt will let the User know all of the foregoing categories of data.

Additional data may be gathered during subsequent or continued use of our Offerings. In order to access/use the Offerings, upon expressly consenting, you may be required, from time to time, at the request of 100xprompt, to provide certain personal data, such as:

• First and last names
• Location (unless disabled by accessing the Device settings)
• Email address
• Residential and/or workplace address
• Mobile number
• Postal code

The foregoing is an inclusive but not an exhaustive list, and such other personal data as may be required from time to time, may be collected and appropriately used after obtaining express consent of the User.

When you use our Product, we collect the information provided by you which includes your inputs, file uploads, outputs generated by the Product.`
  },
  {
    id: "automatic-data",
    title: "Automatically Collected Data",
    content: `We may also automatically receive, collect, store and process certain anonymous data sourced by your usage of the Offerings, such as standard usage logs, through the web server, cookies, standard web log data, traffic to and from our Offerings, tracking within the same, and any other available data from:

• An IP address, assigned to the Device used by the User
• Type of browser used by the User
• The domain server through which the User accesses the Offerings and the functions and features therein
• Queries, comments, or feedback as submitted by the User, including any correspondence you have made with us
• The type/model/make of device used by the User ("Device")

In order to enhance our ability to provide a valuable experience to the Users while accessing/using the Offerings, we may seek and receive one time or continuous access to:

(i) Automatically receive, collect and analyze your location data which may be accessed through a variety of methods including, inter alia, GPS, Internet Protocol address, and cell tower/Device location

(ii) Collect data pertaining to your Device and your usage thereof, including, inter alia, data about your Device, and data about your use of features or functions on your Device

(iii) Camera access to scan/capture/upload documents and/or photographs

(iv) Microphone permissions

(v) Any other files and media

A user may, at any time, revoke access to the aforesaid data through the Device settings.`
  },
  {
    id: "sources",
    title: "Sources of Personal Data",
    content: `We may collect the personal data through various sources, such as those:

• Submitted by yourself, through our Offerings or by contacting/emailing our official contact
• Shared with or by any of our employees and affiliates
• Our sales or marketing representatives (including third party representatives), vendors, suppliers and service providers
• Sourced from public websites and social media, including but not limited to your publicly accessible profiles, etc.
• Sourced via cookies and similar tracking technologies as deployed on our Offerings

It is clarified we do not collect or store any contact (or related) data that may be present on a Device.

It is further clarified that we do not sell your data to any third party under any circumstance as the purpose of collecting data under this Privacy Policy is to deliver/enhance a quality User experience or improve our Offerings in a manner we deem fit and necessary.`
  },
  {
    id: "use-of-data",
    title: "Method and Manner of Use of Data",
    content: `We may use your personal data for the following purposes:

• To provide a meaningful user experience, better usability, troubleshooting and maintenance of our Offerings
• To develop and improve our existing Offerings and such other aspects we deem necessary
• To develop new products, user experience, services, etc.
• For compliance and undertaking of the purchase orders/contract for our products, items or services
• To understand when and which parts of our Offerings are most visited and its frequency
• To identify a User
• To communicate with a User, including contacting and responding to queries or requests and such other communication as may be required
• To communicate special offers and general information about our products, services and events which we may offer that may be similar to those that you have already purchased or enquired about unless the User has opted not to receive such communication/data
• To offer tailored content based on Users' preferences
• To enhance and optimize our company operations, systems, security and processes
• To enable marketing and sales related communications and related purposes
• To protect and defend the rights or property of 100xprompt
• To protect the personal safety of Users of our Offerings and/or the general public
• To protect against or defend any legal liability
• In order to be compliant with applicable law or to honor back-to-back obligations we may have with any other third party in relation to our Offerings

You acknowledge that if we determine that any data you have provided or uploaded violates the terms of this Privacy Policy, we have the right, in our absolute discretion, to delete or destroy such data without incurring any liability to you.

You acknowledge that you are licensing us to use, modify, display, distribute and create new material from the data you provide. By providing such data, you automatically agree, or promise that the owner of such data has expressly agreed to allow or license, as the case may be, us to use the data in the manner set out in this Privacy Policy.

We may, to the extent permitted by law, also use, license, reproduce, distribute disclose, and aggregate, non-personally identifiable data that is derived through your use of our Offerings and you hereby provide consent for the same.`
  },
  {
    id: "sharing",
    title: "Sharing of Data",
    content: `We will not use User data for any purpose other than in connection with Offerings. You understand that we may share the User data with required third parties in connection with our Offerings as may be required and you explicitly agree to such User data being shared.

We may use third party vendors, service providers, including logistic service providers, payment gateway service providers, maintenance service providers, etc. to help us better provide our Offerings to you (for payments and troubleshooting of our Offerings), to whom we may have to disclose your personal data.

Where we use third-party tools, these third parties will have access to some of your personal data, including analytics tools. As may be necessary for managing partnerships, we may also provide deidentified data to our partners relating to the usage of products and services provided by our partners.

When accessing/using the Offerings, in the event you are directed to a third party website or application, and if you choose to access them (or avail what such websites have to offer), we will not be responsible for any such third-party websites or applications. Please note that in case you share any data with such third parties, you will be bound by their respective privacy policies and/or terms of use/service.

100xprompt will not disclose any of the User's personally identifiable data to third parties, save when required under applicable law.

If all or some of the business, stock or assets of 100xprompt are acquired or merged with another business entity, we may share all or some of your data with the acquiring/merged entity.`
  },
  {
    id: "rights",
    title: "Your Rights & Preferences as a Data Subject",
    content: `This Privacy Policy is governed by your rights as per applicable law within the territory from where you access our Offerings.

You shall also be provided with an option to provide or deny consent for use of the data collected for the purposes mentioned in this Privacy Policy, restrict disclosure to third parties, data retention, data rectification, revoke consent already granted to collect data and if required, make us delete/anonymize the data collected by us.

However, in the event of the foregoing, please note that we may not be able to provide all our Offerings efficiently to you.

To the extent applicable under applicable law, you can exercise your rights by submitting a request to the grievance officer.`
  },
  {
    id: "retention",
    title: "Data Retention",
    content: `We take reasonable steps to ensure that User data is available only for so long as is necessary for the purpose for which it is processed, or longer, if required under any applicable law, subject to appropriate safeguards.

Please note that we ensure that all data collected and stored is de-identified. Furthermore, you explicitly consent and agree that we will be entitled to use such de-identified data freely, without any restrictions other than those set out under applicable law.`
  },
  {
    id: "security",
    title: "Data Security",
    content: `The data provided by the User is stored in access controlled facilities with restricted access. User data transmitted over the internet is protected through the use of encryption, using the secure socket layer (SSL) or equivalent protocols.

We shall use generally accepted industry standards to protect the User data submitted to us, both during transmission and upon receipt. However, please be advised that, no method of transmission over the Internet, or method of electronic storage, is 100% secure.

Therefore, even though we strive to use commercially acceptable means to protect User data, we cannot guarantee its absolute security and your use of our Offerings is at your sole risk and discretion. We also cannot warrant that such User data may not be misused in the event our safeguards and protocols are breached maliciously.

Further, we are not liable to, nor can we fully control the actions of other users with whom you may choose to share your data.

The collection, usage, and sharing of User data by us shall be in compliance with applicable laws.

If any security breach comes to our knowledge, then we may take all steps required to protect misuse of such data and may attempt to notify you electronically so that you can take the appropriate steps.`
  },
  {
    id: "eea-uk",
    title: "Other Jurisdictions: Applicability",
    content: `If a User is located in the European Economic Area (EEA), Switzerland or the United Kingdom (UK) or is subject to any personal data laws under the European Union General Data Protection Regulation 2016/679 ("GDPR"), the Data Protection Act, 2018, UK GDPR, along with the terms of this Privacy Policy, the terms set out herein below shall also be applicable.

By using our Offerings, the User acknowledges and agrees to the application of these additional terms:

**Additional Rights**

In addition to the rights mentioned under the Privacy Policy, you have the right to request that we:

• Provide you with a copy of the information we hold about you
• Update any of your personal data if it is inaccurate or out of date
• Delete the personal data we hold about you - if you are using our Product, and you ask us to delete personal data we hold about you then we may be unable to continue providing access to our Platform to you
• Restrict the way in which we process your personal data
• Stop processing your personal data if you have valid objections to such processing
• Transfer your personal data to a third party

**Transfer of Data**

In providing the use/access of the Offerings to you, you understand that we may transfer your information to different locations around the world.

For Users located in the EEA or UK, where your personal data is transferred from the EEA or UK to a recipient outside the EEA or UK to a third country not recognized as providing an adequate level of protection for personal data, such transfer shall be covered by a framework recognized by the relevant authorities or courts as providing an adequate level of protection for personal data, including, but not limited to, Standard Contractual Clauses as approved by the European Commission and any applicable country addenda), the terms of which shall be incorporated by reference.`
  },
  {
    id: "children",
    title: "Children",
    content: `Our Offerings are not in any manner intended for children under the age of 13 (thirteen). We do not knowingly collect any personal data from children below the above-mentioned age.

Further, Persons below the age of 18 (eighteen) years shall use the Service only under strict guidance and supervision of their parents/guardians.`
  },
  {
    id: "updates",
    title: "Privacy Policy Updates",
    content: `We reserve the right to change or update this Privacy Policy at any time. Such changes shall be effective immediately upon us publishing it.

Your access and use of our Offerings following any such change constitutes your agreement to follow and be bound by this Privacy Policy, as updated or modified.

For this reason, we encourage you to review this Privacy Policy each time you access and use our offerings.`
  },
  {
    id: "cookies",
    title: "Cookies",
    content: `When you are using/accessing our Offerings, one or more cookies will be sent to the Device being used by you. The cookies are either used to improve the quality of our Offerings or for storing your preferences as a User, improving the overall User experience.

You have the option of disabling cookies via your Device settings. However, if you disable cookies, some parts of our Offerings may not function in the manner it was designed/intended.

If you would like to disable our access to any passive data we receive from the use of various technologies, you may do so by disabling cookies in your web browser/Device, which may affect the complete use of our Offerings.

Please note that 100xprompt may still receive data about your usage and also your personal data, such as your email address. If you choose to terminate your engagement with 100xprompt, we will store data about you for such period as permitted under applicable law.`
  },
  {
    id: "grievance",
    title: "Nodal Grievance Redressal Officer",
    content: `As required under Information Technology Act, 2000, and rules made thereunder, and for the purposes of addressing complaints, you may contact our nodal grievance redressal officer whose name and contact details are provided below:`
  },
  {
    id: "disputes",
    title: "Dispute Resolution",
    content: `In the event of any dispute, difference or claim arising out of this Privacy Policy the same shall be settled in accordance with the applicable laws in India through regular judicial process and the courts of Bengaluru, India, shall have exclusive jurisdiction.`
  }
];

const tableOfContents = [
  { id: "objective", title: "Objective & Scope" },
  { id: "data-collected", title: "Data Collected" },
  { id: "automatic-data", title: "Automatically Collected Data" },
  { id: "sources", title: "Sources of Personal Data" },
  { id: "use-of-data", title: "Method and Manner of Use of Data" },
  { id: "sharing", title: "Sharing of Data" },
  { id: "rights", title: "Your Rights & Preferences" },
  { id: "retention", title: "Data Retention" },
  { id: "security", title: "Data Security" },
  { id: "eea-uk", title: "Other Jurisdictions" },
  { id: "children", title: "Children" },
  { id: "updates", title: "Privacy Policy Updates" },
  { id: "cookies", title: "Cookies" },
  { id: "grievance", title: "Grievance Redressal" },
  { id: "disputes", title: "Dispute Resolution" },
];

export default function PrivacyPolicyView() {
  const [activeSection, setActiveSection] = useState<string>('objective');
  const mainContentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        });
      },
      {
        rootMargin: '-10% 0px -85% 0px',
        threshold: 0,
      }
    );

    const sections = mainContentRef.current?.querySelectorAll('section[id]');
    sections?.forEach((section) => observer.observe(section));

    return () => observer.disconnect();
  }, []);

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  return (
    <MainLayout>
      <Seo pageKey="privacy" />
      <main className="pt-32 md:pt-40 pb-24 px-6 md:px-12">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <m.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="mb-16"
          >
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-xs font-semibold uppercase tracking-widest mb-8" style={{ background: `${GREEN}12`, color: GREEN }}>
              Legal
            </div>
            
            <h1 
              className="text-4xl sm:text-5xl md:text-6xl font-normal leading-[1.1] tracking-tight mb-6"
              style={{ fontFamily: "'Instrument Serif', Georgia, serif", color: DARK }}
            >
              Privacy Policy
            </h1>
            
            <p className="text-gray-500 text-lg max-w-2xl" style={{ fontFamily: "'DM Sans', sans-serif" }}>
              Updated on: 29th March, 2026
            </p>
          </m.div>

          {/* Intro Box */}
          <m.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="mb-16 p-8 rounded-3xl"
            style={{ 
              background: `linear-gradient(135deg, ${GREEN}08 0%, ${GREEN}03 100%)`,
              border: `1px solid ${GREEN}15`
            }}
          >
            <p className="text-gray-700 leading-relaxed" style={{ fontFamily: "'DM Sans', sans-serif" }}>
              This Privacy Policy ("Privacy Policy") applies to your use of our website <a href="https://100xprompt.com" className="underline" style={{ color: GREEN }}>https://100xprompt.com</a> ("Platform") and products offered through the Platform (hereinafter collectively referred to as "Offerings") which are owned, controlled and operated by <strong>100X Prompt Pvt. Ltd.</strong>, a company incorporated under the laws of India.
            </p>
            <p className="text-gray-700 leading-relaxed mt-4" style={{ fontFamily: "'DM Sans', sans-serif" }}>
              For the purposes of this Privacy Policy, "we", "our" and "us" shall mean the Company and "you" and "your", shall mean a user of the Offerings, whether registered or not ("User").
            </p>
            <p className="text-gray-700 leading-relaxed mt-4 font-medium" style={{ fontFamily: "'DM Sans', sans-serif" }}>
              BY ACCEPTING THE TERMS OF THE PRIVACY POLICY, YOU EXPRESSLY CONSENT TO 100XPROMPT'S COLLECTION, RETENTION, ANALYSIS, USE AND DISCLOSURE OF YOUR PERSONAL DATA IN ACCORDANCE THEREOF.
            </p>
          </m.div>

          {/* Two Column Layout */}
          <div className="grid lg:grid-cols-[280px_1fr] gap-12">
            {/* Table of Contents - Sticky Sidebar */}
            <m.aside
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="hidden lg:block"
            >
              <div className="sticky top-48">
                <h3 
                  className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-4"
                  style={{ fontFamily: "'DM Sans', sans-serif" }}
                >
                  Contents
                </h3>
                <nav className="space-y-1">
                  {tableOfContents.map((item) => {
                    const isActive = activeSection === item.id;
                    return (
                      <button
                        key={item.id}
                        onClick={() => scrollToSection(item.id)}
                        className="block w-full text-left py-2 px-3 rounded-lg transition-all group"
                        style={{ 
                          fontFamily: "'DM Sans', sans-serif",
                          fontSize: '15px',
                          color: isActive ? DARK : 'rgb(75 85 99)',
                        }}
                      >
                        <span className="flex items-center gap-3">
                          <span 
                            className="w-1.5 h-1.5 rounded-full flex-shrink-0 transition-all"
                            style={{
                              background: isActive ? GREEN : 'transparent',
                              boxShadow: isActive ? `0 0 8px ${GREEN}` : 'none',
                            }}
                          />
                          <span className={isActive ? 'font-medium' : 'font-normal group-hover:text-gray-900'}>
                            {item.title}
                          </span>
                        </span>
                      </button>
                    );
                  })}
                </nav>
              </div>
            </m.aside>

            {/* Main Content */}
            <m.div
              ref={mainContentRef}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.8, delay: 0.4 }}
              className="space-y-16"
            >
              {sections.map((section) => (
                <section key={section.id} id={section.id} className="scroll-mt-32">
                  <h2 
                    className="text-2xl md:text-3xl font-semibold mb-6"
                    style={{ fontFamily: "'Instrument Serif', Georgia, serif", color: DARK }}
                  >
                    {section.title}
                  </h2>
                  <div 
                    className="text-gray-600 leading-[1.9] whitespace-pre-line text-[16px]"
                    style={{ fontFamily: "'DM Sans', sans-serif" }}
                  >
                    {section.content}
                  </div>
                  
                  {section.id === "grievance" && (
                    <div 
                      className="mt-8 p-6 rounded-2xl"
                      style={{ background: '#f9fafb', border: '1px solid #e5e7eb' }}
                    >
                      <div className="grid sm:grid-cols-2 gap-6">
                        <div>
                          <p className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-2" style={{ fontFamily: "'DM Sans', sans-serif" }}>
                            Name
                          </p>
                          <p className="text-gray-900 font-medium" style={{ fontFamily: "'DM Sans', sans-serif" }}>
                            Nipurn Agarwal
                          </p>
                        </div>
                        <div>
                          <p className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-2" style={{ fontFamily: "'DM Sans', sans-serif" }}>
                            Email
                          </p>
                          <a 
                            href="mailto:nipurn.agarwal@100xprompt.com" 
                            className="font-medium hover:underline"
                            style={{ color: GREEN }}
                          >
                            nipurn.agarwal@100xprompt.com
                          </a>
                        </div>
                        <div className="sm:col-span-2">
                          <p className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-2" style={{ fontFamily: "'DM Sans', sans-serif" }}>
                            Address
                          </p>
                          <p className="text-gray-900" style={{ fontFamily: "'DM Sans', sans-serif" }}>
                            100xprompt, Bengaluru, Karnataka, India
                          </p>
                        </div>
                      </div>
                    </div>
                  )}
                </section>
              ))}
            </m.div>
          </div>

          {/* Back to top */}
          <m.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.6 }}
            className="mt-16 pt-8 border-t border-gray-100 text-center"
          >
            <button
              onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
              className="inline-flex items-center gap-2 text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors"
              style={{ fontFamily: "'DM Sans', sans-serif" }}
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M18 15l-6-6-6 6" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
              Back to top
            </button>
          </m.div>
        </div>
      </main>

      <CTASection />
    </MainLayout>
  );
}
