export { 
  blogPosts, 
  BLOG_CATEGORIES,
  getPostBySlug,
  getPostsByCategory,
  getFeaturedPosts,
  getRelatedPosts,
  searchPosts,
  getAllPostSlugs,
  getPostsByTag,
  getLatestPosts,
  generatePostSchema,
  generateBlogBreadcrumbSchema,
  type BlogPost,
  type BlogCategorySlug,
} from './posts';
